volumes:
  symfony_db:

services:
  apache:
    container_name: template_symfony_apache
    build: ./docker/build/apache
    ports:
      - '8000:80'
      - '8443:443'
    depends_on:
      - mysql
      - mailpit
    volumes:
      - './docker/etc/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro'
      - './docker/etc/apache/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf'
      - './docker/etc/php/php.ini:/usr/local/etc/php/php.ini'
      - './docker/etc/php/php-cli.ini:/usr/local/etc/php/php-cli.ini'
      - './docker/etc/apache/ssl/:/etc/apache2/conf/ssl'
      - './app/symfony:/var/www/symfony'
  mysql:
    container_name: template_symfony_mysql
    image: mysql:8.0 # Sylius is fully working on mysql 8.0 version
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-symfony_db}
    volumes:
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
      - './docker/etc/mysql/data:/var/lib/mysql:rw'
      - './docker/etc/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    cap_add:
      - SYS_NICE # prevent "mbind: Operation not permitted" errors
    command: [ 'mysqld', '--character-set-server=utf8mb4' ]
  phpmyadmin:
    container_name: template_symfony_phpmyadmin
    ports:
      - '8001:80'
    image: nazarpc/phpmyadmin
    depends_on:
      - mysql
  mailpit:
    image: axllent/mailpit
    container_name: template_symfony_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
